name: frontend
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_functions: ^4.5.8

  # State Management
  flutter_riverpod: ^2.4.9
  
  # Code Generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # Env
  flutter_dotenv: ^5.1.0

  # Other
  cupertino_icons: ^1.0.2
  go_router: ^13.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1

  # Lints
  flutter_lints: ^3.0.1
  
  # Testing
  mockito: ^5.4.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

