name: loyalty_app
description: Loyalty app
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.5.0
  firebase_auth: ^4.2.0
  cloud_firestore: ^4.4.0
  cloud_functions: ^4.3.0
  provider: ^6.0.5
  intl: ^0.18.0
  cupertino_icons: ^1.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
